package cobweb;

public class globals {
	public static RandomNoGenerator random;
	public static RandomNoGenerator behaviorRandom;
	/**
	 * @deprecated Numbers generated by this do not seem to be used
	 */
	@Deprecated
	public static RandomNoGenerator notusedRandom = new RandomNoGenerator(42);
}
