package cobweb;


public class globals {
	public static RandomNoGenerator random;
	public static RandomNoGenerator behaviorRandom;
	/**
	 * @Deprecated Numbers generated by this do not seem to be used
	 */
	@Deprecated
	public static RandomNoGenerator notusedRandom = new RandomNoGenerator(42);
	public static boolean usingTextWindow = false;  // $$$$$$ set to true to enable the output info text window.  Apr 22
}
